
SQL_CAMPAIGN_OVERVIEW = """
SELECT  L.UTM_CAMPAIGN as campaign_name, SUM(LC.TOTALLEAD) AS leads, SUM(IF (LC.LEAD_TYPE='DEMO', LC.DEMODONE,0)) AS demos, 
SUM(LC.CONVERTED) AS enrollments,
MAX(ROUND(IFNULL(LD.SPENT,0),2)) AS spend
FROM LEAD_DEMO_COUNT LC INNER JOIN LEADS L ON L.ID=LC.ID
INNER JOIN LEADS_DETAILS LD ON LD.LEAD_ID=L.ID
LEFT JOIN COUNTRIES C ON C.ID=L.COUNTRY
WHERE LC.INTERESTED_FOR='B2C' AND L.ACTIVE_STATUS='Y' AND L.UTM_CAMPAIGN IS NOT NULL AND L.UTM_CAMPAIGN NOT IN('N/A','N%2FA') 
AND L.UTM_SOURCE NOT IN('ig','fb','an','Test','one', 'demo','th','N%2FA')
AND DATE(L.CREATED_DATE) BETWEEN %s AND %s

"""

SQL_CAMPAIGN_COUNSELOR = """

SELECT  L.UTM_CAMPAIGN as campaign, U.USER_FULL_NAME AS counselor,  SUM(LC.TOTALLEAD) AS leads, 
SUM(IF (LC.LEAD_TYPE='DEMO', LC.DEMODONE,0)) AS demos, 
SUM(LC.CONVERTED) AS enrollments, SUM(L.TOTAL_FOLLOWUP) AS followups
FROM LEAD_DEMO_COUNT LC INNER JOIN 
(SELECT LEADNO,FOLLOW_REMARK_BY,COUNTRY, UTM_CAMPAIGN, COUNT(*)TOTAL_FOLLOWUP 
FROM LEAD_LOGS WHERE SCHEDULE_CALL IS NOT NULL 
AND INTERESTED_FOR='B2C' ACTIVE_STATUS='Y' AND AND UTM_CAMPAIGN IS NOT NULL AND UTM_CAMPAIGN NOT IN('N/A','N%2FA') 
AND  UTM_SOURCE NOT IN('ig','fb', 'an','Test','one',  'demo','th','N%2FA')
AND FOLLOW_REMARK_BY IN(SELECT USER_ID FROM USER_SUPPORT_ROLE_MAPPINGS WHERE ROLE_ID IN(1,2) AND ACTIVE='Y' )
AND DATE(SCHEDULE_CALL) BETWEEN %s AND %s
GROUP BY LEADNO, FOLLOW_REMARK_BY) L 
ON L.LEADNO=LC.LEADNO
LEFT JOIN COUNTRIES C ON C.ID=L.COUNTRY
LEFT JOIN USER U ON U.ID=L.FOLLOW_REMARK_BY
WHERE LC.INTERESTED_FOR='B2C' 

"""

SQL_CAMPAIGN_METRICS = """
SELECT  L.UTM_CAMPAIGN as campaign_name, C.NAME as country, SUM(LC.TOTALLEAD) AS leads, 
SUM(L.TOTAL_FOLLOWUP) AS engaged, SUM(IF (LC.LEAD_TYPE='DEMO', LC.DEMODONE,0)) AS demos, 
SUM(LC.CONVERTED) AS enrollments
FROM LEAD_DEMO_COUNT LC INNER JOIN 
(SELECT LEADNO,FOLLOW_REMARK_BY,COUNTRY, UTM_CAMPAIGN, COUNT(*)TOTAL_FOLLOWUP 
FROM LEAD_LOGS WHERE SCHEDULE_CALL IS NOT NULL 
AND INTERESTED_FOR='B2C' AND ACTIVE_STATUS='Y' AND UTM_CAMPAIGN IS NOT NULL AND UTM_CAMPAIGN NOT IN('N/A','N%2FA') 
AND UTM_SOURCE NOT IN('ig','fb', 'an','Test','one',  'demo','th','N%2FA')
AND FOLLOW_REMARK_BY IN(SELECT USER_ID FROM USER_SUPPORT_ROLE_MAPPINGS WHERE ROLE_ID IN(1,2) AND ACTIVE='Y' )
AND DATE(SCHEDULE_CALL) BETWEEN %s AND %s
GROUP BY LEADNO, FOLLOW_REMARK_BY) L ON L.LEADNO=LC.LEADNO
LEFT JOIN COUNTRIES C ON C.ID=L.COUNTRY
WHERE LC.INTERESTED_FOR='B2C' 

"""

SQL_COUNSELOR_METRICS = """
SELECT  U.ID as counselor_id,  U.USER_FULL_NAME as counselor_name, C.NAME as country,
SUM(LC.TOTALLEAD) AS leads, 
SUM(L.TOTAL_FOLLOWUP) AS engaged,
SUM(IF (LC.LEAD_TYPE='DEMO', LC.DEMODONE,0)) AS demos, 
SUM(LC.CONVERTED) AS enrollments
FROM LEAD_DEMO_COUNT LC INNER JOIN 
(SELECT LEADNO,FOLLOW_REMARK_BY,COUNTRY, UTM_CAMPAIGN, COUNT(LEADNO)TOTAL_FOLLOWUP 
FROM LEAD_LOGS WHERE SCHEDULE_CALL IS NOT NULL 
AND INTERESTED_FOR='B2C' AND ACTIVE_STATUS='Y' 
AND FOLLOW_REMARK_BY IN(SELECT USER_ID FROM USER_SUPPORT_ROLE_MAPPINGS WHERE ROLE_ID IN(1,2) AND ACTIVE='Y' ) 
AND DATE(SCHEDULE_CALL) BETWEEN %s AND %s
GROUP BY LEADNO, FOLLOW_REMARK_BY) L ON L.LEADNO=LC.LEADNO
LEFT JOIN COUNTRIES C ON C.ID=L.COUNTRY
JOIN USER U ON U.ID = L.FOLLOW_REMARK_BY
WHERE LC.INTERESTED_FOR='B2C' 
AND C.NAME IS NOT NULL


"""

SQL_COUNSELOR_CAMPAIGN_METRICS = """
SELECT  L.UTM_CAMPAIGN as campaign_name, 
U.ID as counselor_id, U.USER_FULL_NAME as counselor_name,
C.NAME as country, SUM(LC.TOTALLEAD) AS leads, 
SUM(L.TOTAL_FOLLOWUP) AS engaged, SUM(IF (LC.LEAD_TYPE='DEMO', LC.DEMODONE,0)) AS demos, 
SUM(LC.CONVERTED) AS enrollments
FROM LEAD_DEMO_COUNT LC INNER JOIN 
(SELECT LEADNO,FOLLOW_REMARK_BY,COUNTRY, UTM_CAMPAIGN, COUNT(*)TOTAL_FOLLOWUP 
FROM LEAD_LOGS WHERE SCHEDULE_CALL IS NOT NULL 
AND INTERESTED_FOR='B2C' AND ACTIVE_STATUS='Y' AND UTM_CAMPAIGN IS NOT NULL AND UTM_CAMPAIGN NOT IN('N/A','N%2FA') 
AND UTM_SOURCE NOT IN('ig','fb', 'an','Test','one',  'demo','th','N%2FA')
AND FOLLOW_REMARK_BY IN(SELECT USER_ID FROM USER_SUPPORT_ROLE_MAPPINGS WHERE ROLE_ID IN(1,2) AND ACTIVE='Y' )
AND DATE(SCHEDULE_CALL) BETWEEN %s AND %s
GROUP BY LEADNO, FOLLOW_REMARK_BY) L ON L.LEADNO=LC.LEADNO
LEFT JOIN COUNTRIES C ON C.ID=L.COUNTRY
JOIN USER U ON U.ID = L.FOLLOW_REMARK_BY
WHERE LC.INTERESTED_FOR='B2C' 


"""



